### ISSUE TITLE
关于docker容器迁移的问题

### ISSUE THREAD

**Issue by poiiwe** [hellodk34/lsky-pro-docker#10]
### 有一个问题想请教一下，是关于docker容器迁移的问题。
- 首先，我在第一台机器上部署docker版lsky，docker容器网关为172.18.0.1，使用没有问题
- 之后，我想要把图床程序迁移到另一台机器上，程序部署成功，也可以上传至图床，但是无法拉取图片，存储策略设置保存设置的时候，就提示“服务内部故障”,查看docker容器的网关为172.24.0.1
- 查看docker-compose logs，出现以下问题：
```bash
lsky-pro     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.2. Set the 'ServerName' directive globally to suppress this message
```
实在不知道如何解决这个问题。

**Comment by hellodk34** [comment]
看一下 `存储策略` 里的 `访问网址` 参数是怎么配置的

**Comment by poiiwe** [comment]
访问网址：`https://lsky.balabi.asia/i`
储存路径：`/var/www/html/storage/app/uploads`

**Comment by hellodk34** [comment]
`docker exec -it YOUR_CONTAINER_NAME bash`

进入容器，编辑文件 `/var/www/html/000-default.conf`，手动设置一下 `ServerName`, 取消注释 ServerName 那一行，设置成你的 servername，

```
/var/www/html# cat 000-default.conf 
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
        # ServerName demo.site 

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html/public

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>
```

你试着把 `ServerName demo.site` 改成 `ServerName lsky.balabi.asia` 然后退出容器重启整个 compose 看看。

**Comment by hellodk34** [comment]
更改上面的 ServerName 应该能解决你的问题。不过还有一个思路是在 nginx 反向代理这边，检查 `proxy_pass` 和 `server_name` 两个 key 的 value

**Comment by poiiwe** [comment]
非常感谢你的回答，我马上试一下

**Comment by poiiwe** [comment]
很遗憾并没有解决，/var/www/html是挂载容器外的lsky-pro-db目录下的，我修改了该目录下的000-default.conf文件中的Servername为域名并取消注释，之后执行docker-compose down
docker-compose up -d
但是还是报错。

**Comment by hellodk34** [comment]
可以把 `.env` 里的 `APP_DEBUG` 设成 `true`，然后再看看更详细的日志

**Comment by poiiwe** [comment]
我打开APP_DEBUG之后，重建容器后，点击存储策略设置页面的确认修改后，出现以下异常
### messages
[09:27:13] LOG.error: symlink(): File exists {"userId":1,"exception":{}}

### exceptions

symlink(): File exists*/var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php#335***ErrorException**

```php
    public function link($target, $link)
    {
        if (! windows_os()) {
            return symlink($target, $link);
        }

        $mode = $this->isDirectory($target) ? 'J' : 'H';
```

**Comment by poiiwe** [comment]
我看了一下官方的文档，好像是有提到的，但是对于这点描述的很模糊：
> 如果你使用的是本地储存，请删除 public 目录下的所有符号连接，然后进入后台编辑本地策略，保存一下以重新生成符号连接。

不知道这个符号链接指的是什么?

**Comment by hellodk34** [comment]
Linux 符号链接（Symbolic Link）是一种特殊类型的文件，它指向另一个文件或目录。当我们创建一个符号链接时，它会被赋予一个新的文件名，这个文件名指向了另一个文件或目录的位置。通过符号链接，我们可以在不改变原始文件或目录的情况下，访问它们的副本或别名。

Linux 符号链接可以分为两种类型：

1. 软链接（Soft Link）：也称为符号链接（Symbolic Link），它是一个特殊的文件，它包含了指向另一个文件或目录的路径。软链接可以跨越不同的文件系统，可以指向文件或目录，可以在任何地方创建。

2. 硬链接（Hard Link）：它是一个指向文件或目录的物理链接，它们共享相同的 inode。因此，它们指向的是同一个文件或目录，只是文件名不同。硬链接只能在同一文件系统内创建，并且不能指向目录。

我寻思你一开始的需求不就是迁移一下吗，把你挂载的那个目录 rsync 同步好，再 docker-compose 或者 docker run 挂载跑一个容器应该就能跑了吧……

**Comment by poiiwe** [comment]
我是把整个容器的根目录搬到另一个机器上再docker-compose up -d的,但是没想到出问题了.

**Comment by hellodk34** [comment]
不建议这样做，你直接将挂载的数据目录 rsync 出来然后重新 `docker-compose up -d`，记得检查 `docker-compose.yml` 文件

**Comment by poiiwe** [comment]
这是我的容器根目录结构，数据目录指的是什么？
```bash
.
├── db
├── docker-compose.yml
└── lsky-pro-data
```
目前挂载的是这两个文件夹

这是我的docker-compose.yml

```yaml
version: '3'
services:
    lsky-pro:
        container_name: lsky-pro
        image: dko0/lsky-pro
        restart: always
        volumes:
            - ./lsky-pro-data:/var/www/html  #映射到本地
        ports:
            - 7791:80
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=lsky-pro
            - MYSQL_USER=lsky-pro
            - MYSQL_PASSWORD=lsky-pro

    mysql:
        image: mysql:8.0
        container_name: lsky-pro-db
        restart: always
        environment:
          - MYSQL_DATABASE=lsky-pro
          - MYSQL_USER=lsky-pro
          - MYSQL_PASSWORD=lsky-pro
          - MYSQL_ROOT_PASSWORD=lsky-pro
        volumes:
          - ./db:/var/lib/mysql
```
